"""
orchestrator.py
Ties M1 (adapters/ingestion) -> M2 (features) -> M3 (risk/trajectory) ->
M4 (correlation) -> M5 (knowledge) -> M6 (recommend+safety) -> M7 (explain)
-> M10 (feedback/audit) together per transition. This is the module the API
layer (M8) calls into; it owns the trained models, the analog library, and
the ingestion validator state so a single process can serve the whole
dashboard.
"""

from __future__ import annotations

import threading
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from app.adapters.simulator_adapter import SimulatorAdapter
from app.config import get_actuator_limits, get_settings
from app.contracts import Quality, RiskState
from app.correlation.discovery import discover_correlations, stabilization_impact_ranking
from app.explain.business_impact import estimate_impact
from app.explain.provenance import source_from_correlation
from app.features.feature_engine import MANIPULATED, build_event_features, feature_columns
from app.ingestion.validation import IngestionValidator
from app.knowledge.analogs import AnalogLibrary
from app.knowledge.recipe_limits import RecipeLimitsStore
from app.models.registry import ModelRegistry
from app.models.risk_model import RiskModel
from app.models.trajectory_model import TrajectoryModel
from app.recommend.engine import RecommendationEngine
from app.recommend.safety_gate import check_candidate
from app.simulation.physics_simulator import GRADES
from app.store.db import get_connection
from app.store.feedback_store import expire_stale_suggestions, log_suggestion, mark_superseded

DATA_DIR = Path(__file__).parent.parent / "data"


class GCIOrchestrator:
    def __init__(self):
        self.settings = get_settings()
        self.adapter = SimulatorAdapter()
        self.pt = self.adapter._pt
        self.ge = pd.read_parquet(DATA_DIR / "grade_events.parquet").sort_values("ts_start").reset_index(drop=True)
        self.grade_targets = {g: v["target_bw"] for g, v in GRADES.items()}
        # "Underused site data" per the brief -- generated by the simulator,
        # only used for the Event Timeline (added later; the rest of the
        # system doesn't depend on these, so caching them here is additive).
        self.alarms = pd.read_parquet(DATA_DIR / "alarm_history.parquet")
        self.alarms["ts"] = pd.to_datetime(self.alarms["ts"], utc=True)
        self.actions = pd.read_parquet(DATA_DIR / "operator_actions.parquet")
        self.actions["ts"] = pd.to_datetime(self.actions["ts"], utc=True)

        self.recipe_store = RecipeLimitsStore()
        self.analog_lib = AnalogLibrary(self.pt, self.ge)
        self.recommend_engine = RecommendationEngine(self.analog_lib, self.recipe_store)
        self.risk_model = RiskModel()
        self.trajectory_model = TrajectoryModel()
        self.registry = ModelRegistry()
        self.db = get_connection()

        self._wide_cache: dict[str, pd.DataFrame] = {}
        self._impact_ranking = None
        self._correlations = None
        self._trained = False
        self._risk_state_history: dict[str, dict] = {}
        # FastAPI dispatches sync `def` routes to a thread pool, so concurrent
        # HTTP requests (e.g. rapid slider-drag ticks) call into the SAME
        # XGBoost Booster / SHAP TreeExplainer objects from multiple OS
        # threads at once. Neither is guaranteed safe under concurrent native
        # calls on one instance -- this is what was segfaulting the process.
        # Serializing model inference is the fix; feature building and I/O
        # stay unlocked so they can still overlap.
        self._model_lock = threading.Lock()
        # get_connection() uses check_same_thread=False, which only disables
        # Python's own guard -- it does NOT make the underlying sqlite3
        # connection safe to call concurrently from multiple threads. Every
        # self.db access (here and in routers/feedback.py) MUST hold this
        # lock; without it, concurrent requests segfault inside libsqlite3
        # itself (confirmed via a macOS crash report: thread crashed inside
        # sqlite3Prepare -> sqlite3RunParser -> sqlite3Select).
        self.db_lock = threading.Lock()

    # ------------------------------------------------------------------
    _SEVERITY = {RiskState.OK: 0, RiskState.WATCH: 1, RiskState.AT_RISK: 2, RiskState.CRITICAL: 3}

    def _apply_hysteresis(self, event_id: str, raw_state: RiskState) -> RiskState:
        """E-26: 'risk-state hysteresis (must clear a lower band for 2
        cycles before downgrading)' -- prevents single-cycle noise from
        flapping the displayed state and contributing to alert fatigue.
        Only gates DOWNGRADES (toward less severe); an upgrade (toward more
        severe) is never delayed, since under-warning is the worse failure
        mode. NO_PREDICTION/LOW_CONFIDENCE are data-quality states, not risk
        trend, and pass straight through.

        `raw_history` tracks only ever-raw readings (never overwritten with
        a held/displayed value) so "2 consecutive cycles" means what it says
        on every subsequent call.
        """
        severity = self._SEVERITY
        if raw_state not in severity:
            return raw_state

        slot = self._risk_state_history.setdefault(event_id, {"raw_history": [], "displayed": raw_state})
        raw_history, displayed = slot["raw_history"], slot["displayed"]
        raw_history.append(raw_state)
        del raw_history[:-2]

        if displayed not in severity or severity[raw_state] >= severity[displayed]:
            effective = raw_state  # upgrade or unchanged: never delayed
        elif len(raw_history) >= 2 and all(severity[s] <= severity[raw_state] for s in raw_history[-2:]):
            effective = raw_state  # cleared the lower band for 2 consecutive raw cycles
        else:
            effective = displayed  # hold the more severe state one more cycle

        slot["displayed"] = effective
        return effective

    def wide_for(self, event_id: str) -> pd.DataFrame:
        if event_id not in self._wide_cache:
            ev = self.ge[self.ge["transition_id"] == event_id].iloc[0]
            wide = build_event_features(self.pt, event_id, self.grade_targets[ev["grade_to"]])
            wide["t_stab_s"] = ev["stabilization_time_sec"]
            self._wide_cache[event_id] = wide
        return self._wide_cache[event_id]

    def train(self) -> dict:
        for _, ev in self.ge.iterrows():
            self.wide_for(ev["transition_id"])  # warms cache, used below too

        risk_report = self.risk_model.fit(self.pt, self.ge, self.grade_targets)
        traj_report = self.trajectory_model.fit(self.pt, self.ge, self.grade_targets)

        self.registry.register(
            self.risk_model.model_version, {"note": "risk model artifact (session build)"},
            (self.ge["ts_start"].min(), self.ge["ts_start"].max()), "1.0",
            {"n_estimators": 150, "max_depth": 4}, risk_report,
        )
        self.registry.promote(self.risk_model.model_version)

        self._impact_ranking = stabilization_impact_ranking(self._wide_cache)
        self._correlations = discover_correlations(self._wide_cache)
        self._trained = True
        return {"risk": risk_report, "trajectory": traj_report}

    # ------------------------------------------------------------------
    def list_events(self) -> list[dict]:
        return self.ge[["transition_id", "grade_from", "grade_to", "outcome", "fault_injected",
                         "stabilization_time_sec", "chained", "confounded"]].to_dict(orient="records")

    def correlations(self):
        return self._correlations

    def impact_ranking(self) -> pd.DataFrame:
        return self._impact_ranking

    def _unbiased_median_t_stab(self, from_grade: str, to_grade: str) -> float | None:
        """The plain historical median stabilization time for this grade
        pair -- i.e. NOT biased toward the fastest tercile the way
        AnalogLibrary's recommendation target is. This is the "baseline" the
        Business Impact panel measures improvement against."""
        same_pair = self.ge[(self.ge["grade_from"] == from_grade) & (self.ge["grade_to"] == to_grade)]
        valid = same_pair.dropna(subset=["stabilization_time_sec"])
        if len(valid) < 3:
            return None
        return float(valid["stabilization_time_sec"].median())

    def history(self, event_id: str) -> dict:
        """UX-01: full BW actual/setpoint trend for the trend chart. Spec
        band is +-2.5% of BW_SP (Sec 1.3); the final grade target is constant."""
        ev = self.ge[self.ge["transition_id"] == event_id].iloc[0]
        wide = self.wide_for(event_id)
        band_pct = self.settings.spec.bw_band_pct
        return {
            "t_sec": wide["t_sec"].tolist(),
            "bw_meas": wide["BW_MEAS"].tolist(),
            "bw_sp": wide["BW_SP"].tolist(),
            "hi_spec": (wide["BW_SP"] * (1 + band_pct / 100)).tolist(),
            "lo_spec": (wide["BW_SP"] * (1 - band_pct / 100)).tolist(),
            "final_target_bw": float(self.grade_targets[ev["grade_to"]]),
            "phase": wide["phase"].astype(str).tolist(),
        }

    # ------------------------------------------------------------------
    def tick(self, event_id: str, t_sec: float) -> dict:
        """The core per-cycle snapshot the API/WebSocket layer serves: risk,
        trajectory, an active/new suggestion if warranted, data health, and
        current process state."""
        ev = self.ge[self.ge["transition_id"] == event_id].iloc[0]
        wide = self.wide_for(event_id)
        rows = wide[wide["t_sec"] <= t_sec]
        if rows.empty:
            return {"error": "NO_DATA_AT_T"}
        row = rows.iloc[-1]

        # M1: run this frame through the ingestion validator for a real data-health report.
        validator = IngestionValidator()
        health_report = None
        for f in self.adapter.stream_event(event_id):
            _, health_report = validator.validate(f)
            if (f.ts - rows.iloc[0]["ts"]).total_seconds() >= t_sec:
                break

        no_pred_reason = None
        if health_report and health_report.prediction_disabled:
            no_pred_reason = f"missing_required_tags:{','.join(health_report.missing_required_tags)}"
        elif health_report and health_report.clock_skew_s > self.settings.data.clock_skew_disable_s:
            no_pred_reason = "clock_skew_exceeded"

        feats = {c: row[c] for c in feature_columns() if c in row.index and pd.notna(row[c])}
        with self._model_lock:  # serialize native XGBoost/SHAP calls (see __init__ comment)
            risk = self.risk_model.predict(feats, ev["grade_from"], ev["grade_to"], no_prediction_reason=no_pred_reason)
            trajectory = None
            if no_pred_reason is None:
                trajectory = self.trajectory_model.predict(feats, row["BW_MEAS"], row["BW_SP"], row["BW_MEAS_roc"])
        risk.transition_id = event_id
        risk.state = self._apply_hysteresis(event_id, risk.state)
        if trajectory is not None:
            risk.trajectory = trajectory

        current_values = {tag: float(row[tag]) for tag in MANIPULATED}
        saturation = {tag: bool(row.get(f"{tag}_saturated", False)) for tag in MANIPULATED}

        suggestion, superseded_id, no_suggestion_reason = (None, None, "NO_PREDICTION")
        if no_pred_reason is None and self._impact_ranking is not None:
            suggestion, superseded_id, no_suggestion_reason = self.recommend_engine.maybe_generate(
                event_id, ev["grade_from"], ev["grade_to"], t_sec, current_values, saturation,
                risk, self._impact_ranking, self.risk_model.model_version, datetime.now(timezone.utc),
            )
            if suggestion:
                with self.db_lock:
                    if superseded_id:
                        mark_superseded(self.db, superseded_id)
                    log_suggestion(self.db, suggestion, t_sec=t_sec)

        with self.db_lock:
            expire_stale_suggestions(self.db, datetime.now(timezone.utc), self.settings.suggest.ttl_s)

        # Similar Historical Transitions + Business Impact: an INDEPENDENT
        # analog lookup (not the one inside recommend_engine, which is rate-
        # limited) so these two informational panels stay populated even
        # while the actionable suggestion itself is in its cooldown window --
        # they're reference context, not a new actionable recommendation.
        similar_transitions: list[dict] = []
        business_impact = None
        if no_pred_reason is None:
            analog_values, analogs_info = self.analog_lib.find_analogs(ev["grade_from"], ev["grade_to"], t_sec)
            for tid, outcome in zip(analogs_info.transition_ids, analogs_info.outcomes):
                similar_transitions.append({"transition_id": tid, "outcome": outcome})
            if analog_values:
                recommended_t_stab = analog_values.get("_expected_stabilization_time_sec")
                baseline_t_stab = self._unbiased_median_t_stab(ev["grade_from"], ev["grade_to"])
                business_impact = estimate_impact(
                    current_values.get("MACHINE_SPEED", 0.0), row["BW_MEAS"], baseline_t_stab, recommended_t_stab
                )

        return {
            "event_id": event_id, "t_sec": float(t_sec), "phase": str(row["phase"]),
            "grade_from": ev["grade_from"], "grade_to": ev["grade_to"],
            "current_values": current_values, "saturation": saturation,
            "similar_transitions": similar_transitions, "business_impact": business_impact,
            "bw_meas": float(row["BW_MEAS"]), "bw_sp": float(row["BW_SP"]),
            "bw_deviation_pct": float(row["bw_deviation_pct"]),
            "risk": risk.model_dump(mode="json"),
            "suggestion": suggestion.model_dump(mode="json") if suggestion else None,
            "no_suggestion_reason": no_suggestion_reason,
            "data_health": {
                "missing_required_tags": health_report.missing_required_tags if health_report else [],
                "stale_tags": health_report.stale_tags if health_report else [],
                "clamped_tags": health_report.clamped_tags if health_report else [],
                "prediction_disabled": bool(health_report.prediction_disabled) if health_report else False,
                "confidence_penalty": health_report.confidence_penalty if health_report else 0.0,
            },
        }

    # ------------------------------------------------------------------
    def event_timeline(self, event_id: str) -> list[dict]:
        """Merges the 'underused site data' (alarm history, operator
        actions) with this event's own suggestion log into one chronological
        list -- data that already existed in the system but was never
        surfaced anywhere until now."""
        ev = self.ge[self.ge["transition_id"] == event_id].iloc[0]
        ts_start, ts_end = ev["ts_start"], ev["ts_end"]
        events: list[dict] = []

        for _, a in self.alarms[self.alarms["event_id"] == event_id].iterrows():
            events.append({"t_sec": (a["ts"] - ts_start).total_seconds(), "type": "ALARM", "label": a["alarm"]})

        # operator_actions has no event_id (Sec 5.1.4 schema); a timestamp
        # falling inside this event's window is the join key -- fine for a
        # single-machine dataset, though a chained/overlapping transition
        # could in principle attribute an action to the wrong neighbour.
        in_window = self.actions[(self.actions["ts"] >= ts_start) & (self.actions["ts"] <= ts_end)]
        for _, act in in_window.iterrows():
            delta = act["new_value"] - act["old_value"]
            events.append({
                "t_sec": (act["ts"] - ts_start).total_seconds(), "type": "OPERATOR_ACTION",
                "label": f"{act['operator_id']} adjusted {act['tag']} by {delta:+.2f} "
                         f"({act['old_value']:.2f} -> {act['new_value']:.2f})",
            })

        with self.db_lock:
            rows = self.db.execute(
                "SELECT ts_issued, type, response, t_sec FROM suggestion_feedback WHERE transition_id=?", (event_id,)
            ).fetchall()
        for r in rows:
            # t_sec is the transition's own simulated replay position, stored
            # at generation time -- NOT derived from ts_issued (real
            # wall-clock time), which would produce a nonsensical multi-day
            # figure since the two clocks are unrelated. Rows logged before
            # this field existed have t_sec=NULL; skipped here rather than
            # shown with the old broken math (they're still intact in the
            # Suggestion Log tab's raw table, just not placed on this timeline).
            if r["t_sec"] is None:
                continue
            status = f" -> {r['response']}" if r["response"] else " (pending)"
            events.append({"t_sec": r["t_sec"], "type": "SUGGESTION", "label": f"{r['type']} issued{status}"})

        events.sort(key=lambda e: e["t_sec"])
        return events

    # ------------------------------------------------------------------
    def whatif(self, event_id: str, t_sec: float, overrides: dict[str, float]) -> dict:
        """What-If Simulator: reruns the SAME trained risk/trajectory models
        with one or more manipulated-variable values hypothetically changed,
        so 'what happens if I nudge steam pressure to X' gets a real answer
        from the models rather than a hand-waved guess -- the residual
        correction model was trained on real (feature -> outcome)
        relationships, so perturbing a feature and re-predicting is a
        legitimate (if approximate) counterfactual query, not a fabricated one.
        """
        ev = self.ge[self.ge["transition_id"] == event_id].iloc[0]
        wide = self.wide_for(event_id)
        rows = wide[wide["t_sec"] <= t_sec]
        if rows.empty:
            return {"error": "NO_DATA_AT_T"}
        row = rows.iloc[-1]
        dt_s = self.settings.data.resample_s
        limits = get_actuator_limits()

        base_feats = {c: row[c] for c in feature_columns() if c in row.index and pd.notna(row[c])}
        hyp_feats = dict(base_feats)
        for handle, value in overrides.items():
            if handle not in MANIPULATED:
                continue
            current = float(row[handle])
            hyp_feats[handle] = value
            hyp_feats[f"{handle}_roc"] = (value - current) / dt_s
            lo, hi = limits[handle]["lo"], limits[handle]["hi"]
            hyp_feats[f"{handle}_prox"] = max(0.0, min(1.0, (value - lo) / (hi - lo)))

        with self._model_lock:
            baseline_risk = self.risk_model.predict(base_feats, ev["grade_from"], ev["grade_to"])
            whatif_risk = self.risk_model.predict(hyp_feats, ev["grade_from"], ev["grade_to"])
            baseline_traj = self.trajectory_model.predict(base_feats, row["BW_MEAS"], row["BW_SP"], row["BW_MEAS_roc"])
            whatif_traj = self.trajectory_model.predict(hyp_feats, row["BW_MEAS"], row["BW_SP"], row["BW_MEAS_roc"])

        constraints = self.recipe_store.constraints_for(ev["grade_to"])
        feasibility = [
            check_candidate(handle, float(row[handle]), value, dt_s, constraints,
                             recipe_grade_id=ev["grade_to"]).model_dump(mode="json")
            for handle, value in overrides.items() if handle in MANIPULATED
        ]

        return {
            "event_id": event_id, "t_sec": float(t_sec), "overrides": overrides,
            "baseline_risk": baseline_risk.model_dump(mode="json"),
            "whatif_risk": whatif_risk.model_dump(mode="json"),
            "baseline_trajectory": baseline_traj.model_dump(mode="json"),
            "whatif_trajectory": whatif_traj.model_dump(mode="json"),
            "feasibility": feasibility,
        }


_orchestrator: GCIOrchestrator | None = None


def get_orchestrator() -> GCIOrchestrator:
    global _orchestrator
    if _orchestrator is None:
        _orchestrator = GCIOrchestrator()
        _orchestrator.train()
    return _orchestrator
